import { ProductData } from "@/types";

export const dummyProducts: ProductData[] = [
  {
    id: 1,
    name: "Product 1",
    brand: "Brand A",
    price: 500,
    discountedPrice: 400,
    rating: 4.5,
    numRatings: 20,
    image: "/image1.jpg",
    isInWishlist: false,
  },
  {
    id: 2,
    name: "Product 2",
    brand: "Brand B",
    price: 800,
    discountedPrice: 700,
    rating: 3.8,
    numRatings: 15,
    image: "/image2.jpg",
    isInWishlist: false,
  },
  {
    id: 3,
    name: "Product 3",
    brand: "Brand C",
    price: 1200,
    discountedPrice: 1000,
    rating: 4.8,
    numRatings: 30,
    image: "/image3.jpg",
    isInWishlist: false,
  },
  {
    id: 4,
    name: "Product 4",
    brand: "Brand D",
    price: 1500,
    discountedPrice: 1200,
    rating: 4.2,
    numRatings: 25,
    image: "/image4.jpg",
    isInWishlist: false,
  },
  {
    id: 5,
    name: "Product 5",
    brand: "Brand A",
    price: 2000,
    discountedPrice: 1800,
    rating: 4.7,
    numRatings: 40,
    image: "/image5.jpg",
    isInWishlist: false,
  },
  {
    id: 6,
    name: "Product 6",
    brand: "Brand E",
    price: 800,
    discountedPrice: 600,
    rating: 3.5,
    numRatings: 18,
    image: "/image6.jpg",
    isInWishlist: false,
  },
  {
    id: 7,
    name: "Product 7",
    brand: "Brand B",
    price: 1800,
    discountedPrice: 1500,
    rating: 4.9,
    numRatings: 45,
    image: "/image7.jpg",
    isInWishlist: false,
  },
  {
    id: 8,
    name: "Product 8",
    brand: "Brand C",
    price: 900,
    discountedPrice: 700,
    rating: 3.9,
    numRatings: 22,
    image: "/image8.jpg",
    isInWishlist: false,
  },
  {
    id: 9,
    name: "Product 9",
    brand: "Brand D",
    price: 2500,
    discountedPrice: 2000,
    rating: 4.6,
    numRatings: 35,
    image: "/image9.jpg",
    isInWishlist: false,
  },
  {
    id: 10,
    name: "Product 10",
    brand: "Brand E",
    price: 1200,
    discountedPrice: 900,
    rating: 4.1,
    numRatings: 28,
    image: "/image10.jpg",
    isInWishlist: false,
  },
  {
    id: 11,
    name: "Product 11",
    brand: "Brand A",
    price: 1800,
    discountedPrice: 1600,
    rating: 4.3,
    numRatings: 32,
    image: "/image11.jpg",
    isInWishlist: false,
  },
  {
    id: 12,
    name: "Product 12",
    brand: "Brand B",
    price: 2200,
    discountedPrice: 1900,
    rating: 4.8,
    numRatings: 38,
    image: "/image12.jpg",
    isInWishlist: false,
  },
];
