import { ProductData } from "@/types";

export const dummyProducts: ProductData[] = [
  {
    id: 1,
    name: "Product 1",
    brand: "Brand A",
    price: 500,
    discountedPrice: 400,
    rating: 4.5,
    numRatings: 20,
    image: "/image1.jpg",
    isInWishlist: false,
  },
  {
    id: 2,
    name: "Product 2",
    brand: "Brand B",
    price: 800,
    discountedPrice: 700,
    rating: 3.8,
    numRatings: 15,
    image: "/image2.jpg",
    isInWishlist: false,
  },
  {
    id: 3,
    name: "Product 3",
    brand: "Brand C",
    price: 1200,
    discountedPrice: 1000,
    rating: 4.8,
    numRatings: 30,
    image: "/image3.jpg",
    isInWishlist: false,
  },
  {
    id: 4,
    name: "Product 4",
    brand: "Brand D",
    price: 1500,
    discountedPrice: 1200,
    rating: 4.2,
    numRatings: 25,
    image: "/image4.jpg",
    isInWishlist: false,
  },
  {
    id: 5,
    name: "Product 5",
    brand: "Brand A",
    price: 2000,
    discountedPrice: 1800,
    rating: 4.7,
    numRatings: 40,
    image: "/image5.jpg",
    isInWishlist: false,
  },
  {
    id: 6,
    name: "Product 6",
    brand: "Brand E",
    price: 800,
    discountedPrice: 600,
    rating: 3.5,
    numRatings: 18,
    image: "/image6.jpg",
    isInWishlist: false,
  },
  {
    id: 7,
    name: "Product 7",
    brand: "Brand B",
    price: 1800,
    discountedPrice: 1500,
    rating: 4.9,
    numRatings: 45,
    image: "/image7.jpg",
    isInWishlist: false,
  },
  {
    id: 8,
    name: "Product 8",
    brand: "Brand C",
    price: 900,
    discountedPrice: 700,
    rating: 3.9,
    numRatings: 22,
    image: "/image8.jpg",
    isInWishlist: false,
  },
  {
    id: 9,
    name: "Product 9",
    brand: "Brand D",
    price: 2500,
    discountedPrice: 2000,
    rating: 4.6,
    numRatings: 35,
    image: "/image9.jpg",
    isInWishlist: false,
  },
  {
    id: 10,
    name: "Product 10",
    brand: "Brand E",
    price: 1200,
    discountedPrice: 900,
    rating: 4.1,
    numRatings: 28,
    image: "/image10.jpg",
    isInWishlist: false,
  },
  {
    id: 11,
    name: "Product 11",
    brand: "Brand A",
    price: 1800,
    discountedPrice: 1600,
    rating: 4.3,
    numRatings: 32,
    image: "/image11.jpg",
    isInWishlist: false,
  },
  {
    id: 12,
    name: "Product 12",
    brand: "Brand B",
    price: 2200,
    discountedPrice: 1900,
    rating: 4.8,
    numRatings: 38,
    image: "/image12.jpg",
    isInWishlist: false,
  },
  {
    id: 13,
    name: "Box",
    brand: "Brand E",
    price: 400,
    discountedPrice: 350,
    rating: 4.3,
    numRatings: 28,
    image: "/PMH/Box.jpg",
    isInWishlist: false,
  },
  {
    id: 14,
    name: "Electric wire rope",
    brand: "Brand D",
    price: 2500,
    discountedPrice: 2200,
    rating: 4.7,
    numRatings: 38,
    image: "/PMH/Electric wire rope.jpg",
    isInWishlist: false,
  },
  {
    id: 15,
    name: "Hoists & Trolleys",
    brand: "Brand C",
    price: 17000,
    discountedPrice: 14000,
    rating: 4.8,
    numRatings: 56,
    image: "/PMH/Hoists & Trolleys.jpg",
    isInWishlist: false,
  },
  {
    id: 16,
    name: "Industrial Racks & Storage 2",
    brand: "Brand B",
    price: 22200,
    discountedPrice: 20000,
    rating: 4.5,
    numRatings: 38,
    image: "/PMH/Industrial Racks & Storage 2.jpg",
    isInWishlist: false,
  },
  {
    id: 17,
    name: "Industrial Trolleys",
    brand: "Brand C",
    price: 3300,
    discountedPrice: 3200,
    rating: 3.9,
    numRatings: 28,
    image: "/PMH/Industrial Trolleys.jpg",
    isInWishlist: false,
  },
  {
    id: 18,
    name: "Ladder1",
    brand: "Brand A",
    price: 5500,
    discountedPrice: 5200,
    rating: 4.9,
    numRatings: 38,
    image: "/PMH/Ladder1.jpg",
    isInWishlist: false,
  },
  {
    id: 19,
    name: "Material Lifts",
    brand: "Brand B",
    price: 8000,
    discountedPrice: 7200,
    rating: 4,
    numRatings: 44,
    image: "/PMH/Material Lifts.jpg",
    isInWishlist: false,
  },
  {
    id: 20,
    name: "Material-Handling",
    brand: "Brand A",
    price: 28000,
    discountedPrice: 25000,
    rating: 4.3,
    numRatings: 58,
    image: "/PMH/Material-Handling.jpg",
    isInWishlist: false,
  },
  {
    id: 21,
    name: "Packaging Machines 1",
    brand: "Brand E",
    price: 33500,
    discountedPrice: 31800,
    rating: 3.8,
    numRatings: 28,
    image: "/PMH/Packaging Machines 1.jpg",
    isInWishlist: false,
  },
  {
    id: 22,
    name: "Packaging Machines 3",
    brand: "Brand A",
    price: 16000,
    discountedPrice: 15000,
    rating: 3,
    numRatings: 70,
    image: "/PMH/Packaging Machines 3.jpg",
    isInWishlist: false,
  },

  {
    id: 23,
    name: "Packaging Machines 4",
    brand: "Brand D",
    price: 14000,
    discountedPrice: 12000,
    rating: 3.9,
    numRatings: 85,
    image: "/PMH/Packaging Machines 4.jpg",
    isInWishlist: false,
  },
  {
    id: 24,
    name: "Packaging Machines 5",
    brand: "Brand C",
    price: 19000,
    discountedPrice: 17000,
    rating: 4.9,
    numRatings: 23,
    image: "/PMH/Packaging Machines 5.jpg",
    isInWishlist: false,
  },
  {
    id: 25,
    name: "Packaging Rolls 1",
    brand: "Brand D",
    price: 1600,
    discountedPrice: 1500,
    rating: 4.3,
    numRatings: 44,
    image: "/PMH/Packaging Rolls 1.jpg",
    isInWishlist: false,
  },
  {
    id: 26,
    name: "Packaging Rolls 2",
    brand: "Brand E",
    price: 760,
    discountedPrice: 650,
    rating: 2.5,
    numRatings: 10,
    image: "/PMH/Packaging Rolls 2.jpg",
    isInWishlist: false,
  },
  {
    id: 27,
    name: "Packaging-Material-&-Supplies",
    brand: "Brand A",
    price: 1200,
    discountedPrice: 1100,
    rating: 4.5,
    numRatings: 43,
    image: "/PMH/Packaging-Material-&-Supplies.jpg",
    isInWishlist: false,
  },
  {
    id: 28,
    name: "pulley",
    brand: "Brand D",
    price: 600,
    discountedPrice: 500,
    rating: 4.2,
    numRatings: 72,
    image: "/PMH/pulley.jpg",
    isInWishlist: false,
  },
  {
    id: 29,
    name: "Rope & Fittings 1",
    brand: "Brand A",
    price: 1800,
    discountedPrice: 1750,
    rating: 4.1,
    numRatings: 66,
    image: "/PMH/Rope & Fittings 1.jpg",
    isInWishlist: false,
  },
  {
    id: 30,
    name: "Rope & Fittings 2",
    brand: "Brand E",
    price: 16000,
    discountedPrice: 15000,
    rating: 4.9,
    numRatings: 70,
    image: "/PMH/Rope & Fittings 2.jpg",
    isInWishlist: false,
  },
  {
    id: 31,
    name: "Tarpaulin 1",
    brand: "Brand C",
    price: 1300,
    discountedPrice: 1250,
    rating: 4.2,
    numRatings: 39,
    image: "/PMH/Tarpaulin 1.jpg",
    isInWishlist: false,
  },
  {
    id: 32,
    name: "Tarpaulin 2",
    brand: "Brand C",
    price: 750,
    discountedPrice: 600,
    rating: 3.6,
    numRatings: 51,
    image: "/PMH/Tarpaulin 2.jpg",
    isInWishlist: false,
  },
  {
    id: 33,
    name: "Abrasives",
    brand: "Brand D",
    price: 400,
    discountedPrice: 300,
    rating: 3.7,
    numRatings: 33,
    image: "/ITM/Abrasives.jpg",
    isInWishlist: false,
  },
  {
    id: 34,
    name: "Cutting-tools",
    brand: "Brand D",
    price: 2700,
    discountedPrice: 2500,
    rating: 3.4,
    numRatings: 45,
    image: "/ITM/Cutting-tools.jpg",
    isInWishlist: false,
  },
  {
    id: 35,
    name: "Fasteners",
    brand: "Brand D",
    price: 200,
    discountedPrice: 150,
    rating: 4.6,
    numRatings: 66,
    image: "/ITM/Fasteners.jpg",
    isInWishlist: false,
  },
  {
    id: 36,
    name: "Fasteners1",
    brand: "Brand D",
    price: 250,
    discountedPrice: 200,
    rating: 4.6,
    numRatings: 48,
    image: "/ITM/Fasteners1.jpg",
    isInWishlist: false,
  },
  {
    id: 37,
    name: "Hand tools",
    brand: "Brand A",
    price: 800,
    discountedPrice: 760,
    rating: 4.2,
    numRatings: 36,
    image: "/ITM/Hand tools.jpg",
    isInWishlist: false,
  },
  {
    id: 38,
    name: "Hydraulics",
    brand: "Brand B",
    price: 36000,
    discountedPrice: 34000,
    rating: 4.2,
    numRatings: 55,
    image: "/ITM/Hydraulics.jpg",
    isInWishlist: false,
  },
  {
    id: 39,
    name: "Material Handling and Packagings",
    brand: "Brand A",
    price: 46000,
    discountedPrice: 41000,
    rating: 4.6,
    numRatings: 48,
    image: "/ITM/Material Handling and Packagings.jpg",
    isInWishlist: false,
  },
  {
    id: 40,
    name: "Pneumatics",
    brand: "Brand B",
    price: 56000,
    discountedPrice: 52000,
    rating: 4.3,
    numRatings: 29,
    image: "/ITM/Pneumatics.jpg",
    isInWishlist: false,
  },
  {
    id: 41,
    name: "Power tool",
    brand: "Brand C",
    price: 6000,
    discountedPrice: 4500,
    rating: 4.3,
    numRatings: 19,
    image: "/ITM/Power tool.jpg",
    isInWishlist: false,
  },
  {
    id: 42,
    name: "1-ACC-Blocks",
    brand: "Brand D",
    price: 600,
    discountedPrice: 500,
    rating: 4.9,
    numRatings: 80,
    image: "/RCC/1-ACC-Blocks.jpg",
    isInWishlist: false,
  },
  {
    id: 43,
    name: "2-ACC-Blocks",
    brand: "Brand D",
    price: 1000,
    discountedPrice: 900,
    rating: 4.9,
    numRatings: 80,
    image: "/RCC/2-ACC-Blocks.jpg",
    isInWishlist: false,
  },
  {
    id: 44,
    name: "3-ACC-Blocks",
    brand: "Brand D",
    price: 1400,
    discountedPrice: 1250,
    rating: 4.9,
    numRatings: 80,
    image: "/RCC/3-ACC-Blocks.jpg",
    isInWishlist: false,
  },
  {
    id: 46,
    name: "ArtMix",
    brand: "Brand C",
    price: 1700,
    discountedPrice: 1500,
    rating: 5,
    numRatings: 140,
    image: "/RCC/ArtMix.jpg",
    isInWishlist: false,
  },
  {
    id: 47,
    name: "Coarse Aggregates",
    brand: "Brand C",
    price: 4600,
    discountedPrice: 4200,
    rating: 5,
    numRatings: 150,
    image: "/RCC/Coarse Aggregates.jpg",
    isInWishlist: false,
  },
  {
    id: 48,
    name: "FibreMix Concrete",
    brand: "Brand C",
    price: 4800,
    discountedPrice: 4700,
    rating: 5,
    numRatings: 190,
    image: "/RCC/FibreMix Concrete.jpg",
    isInWishlist: false,
  },
  {
    id: 49,
    name: "Fine-Aggregates",
    brand: "Brand C",
    price: 7600,
    discountedPrice: 6800,
    rating: 5,
    numRatings: 160,
    image: "/RCC/Fine-Aggregates.jpg",
    isInWishlist: false,
  },
  {
    id: 50,
    name: "FloorMix Concrete",
    brand: "Brand E",
    price: 10000,
    discountedPrice: 8000,
    rating: 5,
    numRatings: 170,
    image: "/RCC/FloorMix Concrete.jpg",
    isInWishlist: false,
  },
  {
    id: 51,
    name: "FotiMix Concrete",
    brand: "Brand E",
    price: 12000,
    discountedPrice: 10000,
    rating: 5,
    numRatings: 120,
    image: "/RCC/FotiMix Concrete.jpg",
    isInWishlist: false,
  },
  {
    id: 52,
    name: "LiteMix Concrete",
    brand: "Brand E",
    price: 13000,
    discountedPrice: 12000,
    rating: 5,
    numRatings: 160,
    image: "/RCC/LiteMix Concrete.jpg",
    isInWishlist: false,
  },
  {
    id: 53,
    name: "PoreMix Concrete",
    brand: "Brand D",
    price: 14000,
    discountedPrice: 13000,
    rating: 5,
    numRatings: 140,
    image: "/RCC/PoreMix Concrete.jpg",
    isInWishlist: false,
  },
  {
    id: 54,
    name: "Sand",
    brand: "Brand E",
    price: 400,
    discountedPrice: 300,
    rating: 4.5,
    numRatings: 140,
    image: "/RCC/Sand.jpg",
    isInWishlist: false,
  },
  {
    id: 55,
    name: "SelfMix",
    brand: "Brand B",
    price: 700,
    discountedPrice: 600,
    rating: 4.5,
    numRatings: 10,
    image: "/RCC/SelfMix.jpg",
    isInWishlist: false,
  },
  {
    id: 56,
    name: "SpineMix Concrete",
    brand: "Brand B",
    price: 600,
    discountedPrice: 500,
    rating: 4.3,
    numRatings: 18,
    image: "/RCC/SpineMix Concrete.jpg",
    isInWishlist: false,
  },
  {
    id: 57,
    name: "QuickMix",
    brand: "Brand D",
    price: 800,
    discountedPrice: 600,
    rating: 4.3,
    numRatings: 39,
    image: "/RCC/QuickMix.jpg",
    isInWishlist: false,
  },
  {
    id: 58,
    name: "Fall Protection",
    brand: "Brand C",
    price: 2000,
    discountedPrice: 1800,
    rating: 4,
    numRatings: 77,
    image: "/PPE/Fall Protection.jpg",
    isInWishlist: false,
  },
  {
    id: 59,
    name: "Fire Extinguisher",
    brand: "Brand B",
    price: 3600,
    discountedPrice: 2800,
    rating: 3,
    numRatings: 79,
    image: "/PPE/Fire Extinguisher.jpg",
    isInWishlist: false,
  },
  {
    id: 60,
    name: "Respiratory-mask",
    brand: "Brand B",
    price: 60,
    discountedPrice: 40,
    rating: 3.9,
    numRatings: 42,
    image: "/PPE/Respiratory-mask.jpg",
    isInWishlist: false,
  },
  {
    id: 61,
    name: "Safety shoes",
    brand: "Brand C",
    price: 6000,
    discountedPrice: 4000,
    rating: 4.4,
    numRatings: 57,
    image: "/PPE/Safety shoes.jpg",
    isInWishlist: false,
  },
  {
    id: 62,
    name: "Safety-gloves",
    brand: "Brand C",
    price: 600,
    discountedPrice: 400,
    rating: 4.7,
    numRatings: 67,
    image: "/PPE/Safety-gloves.jpg",
    isInWishlist: false,
  },
  {
    id: 63,
    name: "Safety-helmets",
    brand: "Brand C",
    price: 7000,
    discountedPrice: 6000,
    rating: 4.8,
    numRatings: 68,
    image: "/PPE/Safety-helmets.jpg",
    isInWishlist: false,
  },
  {
    id: 64,
    name: "Safety-jackets",
    brand: "Brand D",
    price: 1700,
    discountedPrice: 1500,
    rating: 4.4,
    numRatings: 58,
    image: "/PPE/Safety-jackets.jpg",
    isInWishlist: false,
  },
];
